config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :instruments, :except => [:index, :show]
  resources :users, :except => [:new]
  resources :shop, controller: 'instruments', :only => [:index, :show]
  resources :product_types

  get 'contacts', to: 'contacts#index'
  get :shopping_carts, :path => 'cart', to: 'shopping_carts#index'

  root to: 'welcome#index'
end

app/controllers/product_types_controller.rb
class ProductTypesController < ApplicationController
  before_action :set_product_type, only: [:show, :edit, :update, :destroy]

  def index
    @product_types = ProductType.all
  end

  def show
  end

  def new
    @product_type = ProductType.new
  end

  def edit
  end

  def create
    @product_type = ProductType.new(product_type_params)

    respond_to do |format|
      if @product_type.save
        format.html { redirect_to @product_type, notice: 'Product type was successfully created.' }
        format.json { render :show, status: :created, location: @product_type }
      else
        format.html { render :new }
        format.json { render json: @product_type.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product_type.update(product_type_params)
        format.html { redirect_to @product_type, notice: 'Product type was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_type }
      else
        format.html { render :edit }
        format.json { render json: @product_type.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product_type.destroy
    respond_to do |format|
      format.html { redirect_to product_types_url, notice: 'Product type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_product_type
    @product_type = ProductType.find(params[:id])
  end

  def product_type_params
    params.require(:product_type).permit(:type_name)
  end
end

app/helpers/product_types_helper.rb
module ProductTypesHelper
end

app/views/product_types/_form.html.erb
<%= form_with(model: product_type, local: true) do |form| %>
  <% if product_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product_type.errors.count, "error") %> prohibited this product_type from being saved:</h2>

      <ul>
      <% product_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :type_name %>
    <%= form.text_field :type_name, class:"form-control" %>
  </div>

  <div class="actions">
    <%= form.submit nil, class: "btn btn-primary" %>
  </div>
<% end %>

</br>

app/views/product_types/create.html.erb
<h1>ProductTypes#create</h1>
<p>Find me in app/views/product_types/create.html.erb</p>

app/views/product_types/destroy.html.erb
<h1>ProductTypes#destroy</h1>
<p>Find me in app/views/product_types/destroy.html.erb</p>

app/views/product_types/edit.html.erb
<h1><%= t('editing.product_type') %></h1>

<%= render 'form', product_type: @product_type %>

<%= link_to t('links.show'), @product_type %> |
<%= link_to t('links.back'), product_types_path %>

app/views/product_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= ProductType.model_name.human(count: @product_types.count) %></h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th><%= @product_types.human_attribute_name(:type_name) %></th>
      <th><%= @product_types.human_attribute_name(:type_name) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @product_types.each do |product_type| %>
      <tr>
        <td><%= product_type.type_name %></td>
        <td><%= link_to t('links.show'), product_type %></td>
        <td><%= link_to t('links.edit'), edit_product_type_path(product_type) %></td>
        <td><%= link_to t('links.delete'), product_type, method: :delete, data: { confirm: t('messages.confirm') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('new.product_type'), new_product_type_path, class:"btn btn-primary" %>

app/views/product_types/new.html.erb
<h1><%= t('new.product_type') %></h1>

<%= render 'form', product_type: @product_type %>

<%= link_to t('links.back'), product_types_path, class: "btn btn-primary" %>

app/views/product_types/show.html.erb
<p id="notice"><%= notice %></p>

<form>

  <div class="form-group">
    <%= label_tag nil, @product_type.class.human_attribute_name(:type_name) %>
    <%= text_field_tag nil, @product_type.type_name, class:"form-control", disabled:true %>
  </div>

</form>

<%= link_to t('links.edit'), edit_product_type_path(@product_type), class: "btn btn-primary" %> |
<%= link_to t('links.back'), product_types_path, class: "btn btn-primary" %>

app/views/product_types/update.html.erb
<h1>ProductTypes#update</h1>
<p>Find me in app/views/product_types/update.html.erb</p>