config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :instruments, :except => [:index, :show]
  resources :users, :except => [:new]
  resources :shop, controller: 'instruments', :only => [:index, :show]
  resources :product_types

  get 'contacts', to: 'contacts#index'
  get :shopping_carts, :path => 'cart', to: 'shopping_carts#index'

  root to: 'welcome#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, :last_name, :birth_date, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :user?, only: [:index, :show, :edit, :destroy]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :birth_date, :email)
  end

  def user?
    if current_user.admin == true
      return true
    elsif current_user.id != params[:id].to_i
      redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= form_with model: @user do |form| %>

<div class="container light-style flex-grow-1 container-p-y">

    <h4 class="font-weight-bold py-3 mb-4">
      Edit settings
    </h4>

    <div class="card overflow-hidden">
      <div class="row no-gutters row-bordered row-border-light">
        <div class="col-md-9">
          <div class="tab-content">
            <div class="tab-pane fade active show">

              <hr class="border-light m-0">

              <div class="card-body">
                <div class="form-group">
                  <%= form.label :first_name, class:'form-label' %>
                  <%= form.text_field :first_name, class:'form-control' %>
                </div>
                <div class="form-group">
                  <%= form.label :last_name, class:'form-label' %><br>
                  <%= form.text_field :last_name, class:'form-control' %>
                </div>
                <div class="form-group">
                  <%= form.label :birth_date, class:'form-label' %><br>
                  <%= form.date_field :birth_date, class:'form-control mb-1' %>
                </div>
                <div class="form-group">
                  <%= form.label :address, class:'form-label' %>
                  <%= form.text_field :address, class:'form-control' %>
                </div>
                <div class="form-group">
                  <%= form.label :phone, class:'form-label' %>
                  <%= form.text_field :phone, class:'form-control' %>
                </div>
                <div class="form-group">
                  <%= form.label :email, class:'form-label' %><br>
                  <%= form.email_field :email, class:'form-control mb-1' %>
                </div>
                <div class="form-group">
                  <%= form.label :password, class:'form-label' %><br>
                  <%= form.password_field :password, class:'form-control' %>
                </div>
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="text-right mt-3">
      <%= form.submit 'Save changes', class:'btn btn-primary' %>
      <%= link_to 'Cancel', user_path, class:'btn btn-default' %>
    </div>

  </div>
<% end %>

app/views/users/index.html.erb
<div class="list-group m-5">
  <h1 class="mb-3">List of all users</h1>

  <% @users.each do |user| %>
    <%= link_to user.first_name, user, class:"list-group-item list-group-item-action" %>
  <% end %>

  <div class="text-left mt-3">
    <%= link_to 'Back', :back, class:'btn btn-primary' %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container light-style flex-grow-1 container-p-y">

    <h4 class="font-weight-bold py-3 mb-4">
      Account settings
    </h4>

    <div class="card overflow-hidden">
      <div class="row no-gutters row-bordered row-border-light">
        <div class="col-md-3 pt-0">
          <div class="list-group list-group-flush account-settings-links">
            <a class="list-group-item list-group-item-action active" data-toggle="list" href="#account-general">General</a>
            <a class="list-group-item list-group-item-action" data-toggle="list" href="#account-edit">Edit Account</a>
            <a class="list-group-item list-group-item-action" data-toggle="list" href="#account-delete">Delete Account</a>
            <% if current_user.admin == true %>
              <a class="list-group-item list-group-item-action" data-toggle="list" href="#account-admin-option">Admin Option</a>
            <% end %>
          </div>
        </div>
        <div class="col-md-9">
          <div class="tab-content">
            <div class="tab-pane fade active show" id="account-general">

              <hr class="border-light m-0">

              <div class="card-body">
                <div class="form-group mb-2">
                  <label class="form-label">First Name</label>
                  <span class="input-group-text"><%= @user.first_name %></span>
                </div>
                <div class="form-group mb-2">
                  <label class="form-label">Last Name</label>
                  <span class="input-group-text"><%= @user.last_name %></span>
                </div>
                <div class="form-group mb-2">
                  <label class="form-label">Birth Date</label>
                  <span class="input-group-text"><%= @user.birth_date %></span>
                </div>
                <div class="form-group mb-2">
                  <label class="form-label">Phone</label>
                  <span class="input-group-text"><%= @user.phone ? @user.phone : 'Empty' %></span>
                </div>
                <div class="form-group mb-2">
                  <label class="form-label">Address</label>
                  <span class="input-group-text"><%= @user.address ? @suer.address : 'Empty' %></span>
                </div>
                <div class="form-group mb-2">
                  <label class="form-label">E-mail</label>
                  <span class="input-group-text"><%= @user.email %></span>
                </div>
              </div>

            </div>
            <div class="tab-pane fade" id="account-edit">
              <div class="card-body pb-2">

                <div class="form-group">
                  <%= link_to "Edit Account", edit_user_path(@user), class: 'btn btn-info' %><br>
                </div>

              </div>
            </div>
            <div class="tab-pane fade" id="account-delete">
              <div class="card-body pb-2">
                <div class="form-group">
                  <%= link_to "Delete Account", user_path(@user),
                              method: :delete,
                              data: { confirm: "Are you sure?" },
                              class: 'btn btn-danger' %>
                </div>
              </div>
            </div>

            <% if current_user.admin == true %>
              <div class="tab-pane fade" id="account-admin-option">
                <div class="card-body border">
                  <form class="form-inline">
                    <div class="form-group mb-2">
                      <input type="text" readonly class="form-control-plaintext font-weight-bold my-1" value="Add instruments in stock:">
                    </div>
                    <%= link_to 'Add Instrument', new_instrument_path, class:"btn btn-primary" %>
                  </form>

                  <form class="form-inline">
                    <div class="form-group mb-2">
                      <input type="text" readonly class="form-control-plaintext font-weight-bold my-1" value="Show all Users:">
                    </div>
                    <%= link_to 'Show Users', users_path, class:"btn btn-success" %>
                  </form>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="text-left mt-3">
      <%= link_to 'Back', root_path, class:'btn btn-primary' %>
    </div>

  </div>