config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :instruments, :except => [:index, :show]
  resources :users, :except => [:new]
  resources :shop, controller: 'instruments', :only => [:index, :show]
  resources :product_types

  get 'contacts', to: 'contacts#index'
  get :shopping_carts, :path => 'cart', to: 'shopping_carts#index'

  root to: 'welcome#index'
end

app/models/instrument.rb
class Instrument < ApplicationRecord
  belongs_to :product_type
  has_many :orderables
  has_many :shopping_carts, through: :orderables

  validates :name, presence: true
  validates :model, presence: true
  validates :brand, presence: true
  validates :price, presence: true #, length: { minimum: 1 }

  has_one_attached :photo
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :admin?, only: [:new, :edit, :destroy]
  before_action :set_product_type_options, only: [:new, :create, :edit, :update]

  def index
    @instruments = Instrument.all
  end

  def show
    @instrument = Instrument.find(params[:id])
    @instruments = Instrument.all
  end

  def new
    @instrument = Instrument.new
  end

  def edit
    @instrument = Instrument.find(params[:id])
  end

  def create
    @instrument = Instrument.new(instrument_params)

    if @instrument.save
      redirect_to shop_index_path 
    else
      render :new
    end
  end

  def update
    @instrument = Instrument.find(params[:id])

    if @instrument.update(instrument_params)
      redirect_to shop_index_path
    else
      render :edit
    end
  end

  def destroy
    @instrument = Instrument.find(params[:id])
    @instrument.destroy

    redirect_to shop_index_path
  end

  private

  def instrument_params
    params.require(:instrument).permit(:name, :model, :brand, :price, :description, :photo, :product_type_id)
  end

  def admin?
    if current_user.admin == true
      return true
    else 
      redirect_to root_path
    end
  end

  def set_product_type_options
    @product_type_options = ProductType.all.pluck(:type_name, :id)
  end
end

app/helpers/instruments_helper.rb
module InstrumentsHelper
  def show_instrument(instrument, instrument_name, instrument_model, instrument_brand, instrument_price, instrument_photo, type_product)
    if instrument.product_type.type_name == type_product
      content_tag(:div, class:'col mb-5 hover-shadow d-flex justify-content-start p-0 mx-2', style:'max-width:240px;max-height:550px;') do
        concat(content_tag(:div, class:'card h-100') do
          if instrument_photo.attached?
            concat image_tag instrument_photo, class: 'card-img-top', style: 'height:350px;width:auto;' if instrument_photo.attached?
          else
            concat(content_tag(:img, '', class:'card-img-top',style:'height:350px;width:238px;background-color:gray;border:solid 1px gray;'))
          end

          concat(content_tag(:div, class:'card-body p-4') do
            concat(content_tag(:div, class:'text-center') do
              concat(content_tag(:h5, instrument_name + ", " + instrument_model +" "+ instrument_brand, class:'fw-bolder'))
              concat(content_tag(:div, class:'d-flex justify-content-center small text-warning mb-2') do
                concat(content_tag(:div, '', class:'bi-star-fill'))
                concat(content_tag(:div, '', class:'bi-star-fill'))
                concat(content_tag(:div, '', class:'bi-star-fill'))
                concat(content_tag(:div, '', class:'bi-star-fill'))
                concat(content_tag(:div, '', class:'bi-star-fill'))
              end)

              concat(content_tag(:p, "Price: R$ " + instrument_price.to_s, class:'card-text'))
            end)
          end)
        end)
        concat link_to '', shop_path(instrument), class:'mt-auto stretched-link'
      end
    elsif type_product == ''
      content_tag(:div, class:'col mb-5 hover-shadow d-flex justify-content-start p-0 mx-2', style:'max-width:240px;max-height:550px;') do
        concat(content_tag(:div, class:'card h-100') do
          if instrument_photo.attached?
            concat image_tag instrument_photo, class: 'card-img-top', style: 'height:350px;width:auto;' if instrument_photo.attached?
          else
            concat(content_tag(:img, '', class:'card-img-top',style:'height:350px;width:238px;background-color:gray;border:solid 1px gray;'))
          end

          concat(content_tag(:div, class:'card-body p-4') do
            concat(content_tag(:div, class:'text-center') do
              concat(content_tag(:h5, instrument_name + ", " + instrument_model +" "+ instrument_brand, class:'fw-bolder'))
              concat(content_tag(:div, class:'d-flex justify-content-center small text-warning mb-2') do
                concat(content_tag(:div, '', class:'bi-star-fill'))
                concat(content_tag(:div, '', class:'bi-star-fill'))
                concat(content_tag(:div, '', class:'bi-star-fill'))
                concat(content_tag(:div, '', class:'bi-star-fill'))
                concat(content_tag(:div, '', class:'bi-star-fill'))
              end)

              concat(content_tag(:p, "Price: R$ " + instrument_price.to_s, class:'card-text'))
            end)
          end)
        end)
        concat link_to '', shop_path(instrument), class:'mt-auto stretched-link'
      end
    end
  end
end

app/views/instruments/_form.html.erb
<%= form_with model: instrument do |form| %>

<div class="card overflow-hidden">
  <div class="row no-gutters row-bordered row-border-light">
    <div class="col-md-9">
      <div class="tab-content">
        <div class="tab-pane fade active show">

        <hr class="border-light m-0">

        <div class="card-body">
          <div class="form-group">
            <%= form.label :name %><br>
            <%= form.text_field :name, class:'form-control' %>
            <% instrument.errors.full_messages_for(:name).each do |message| %>
              <div><%= message %></div>
            <% end %>
          </div>

          <div class="form-group">
            <%= form.label :model %><br>
            <%= form.text_field :model, class:'form-control' %>
            <% instrument.errors.full_messages_for(:model).each do |message| %>
              <div><%= message %></div>
            <% end %>
          </div>

          <div class="form-group">
            <%= form.label :brand %><br>
            <%= form.text_field :brand, class:'form-control' %>
            <% instrument.errors.full_messages_for(:brand).each do |message| %>
              <div><%= message %></div>
            <% end %>
          </div>

          <div class="form-group">
            <%= form.label :price %><br>
            <%= form.number_field :price, min: 1.0, step: 0.5, class:'form-control' %>
            <% instrument.errors.full_messages_for(:price).each do |message| %>
              <div><%= message %></div>
            <% end %>
          </div>

          <div class="form-group">
            <%= form.label :description %>
            <%= form.text_area :description, class:'form-control', rows:'3' %>
          </div> 

          <div class="form-group">
            <%= form.label :product_type_id %>
            <%= form.select("product_type_id", @product_type_options, { include_blank: 'Select...' }, class:"form-control") %>
          </div>

          <div class="form-group">
            <%= form.label :photo %><br>
            <%= form.file_field :photo, class:'form-control' %>
          </div>
        </div>

        </div>
      </div>
    </div>
  </div>
</div>

<div class="text-right my-3">
  <%= form.submit class: "btn btn-primary"%>
</div>

<% end %>

app/views/instruments/edit.html.erb
<div class="container light-style flex-grow-1 container-p-y">

<h4 class="font-weight-bold py-3 mb-4">
  New Instruments
</h4>

<%= render "form", instrument: @instrument %>

</div>

app/views/instruments/index.html.erb
<%= render 'layouts/navbar' %>

<div class="row gx-0 m-auto">
  <div class="col-2 p-0">
    <div class="list-group" id="list-tab" role="tablist">
      <a class="list-group-item list-group-item-primary">Instrument types</a>
      <a class="list-group-item list-group-item-action active" data-toggle="list" href="#list-all" role="tab" aria-controls="home">All</a>
      <a class="list-group-item list-group-item-action" data-toggle="list" href="#list-guitar" role="tab" aria-controls="profile">Guitar</a>
      <a class="list-group-item list-group-item-action" data-toggle="list" href="#list-electric-guitar" role="tab" aria-controls="profile">Electric Guitar</a>
      <a class="list-group-item list-group-item-action" data-toggle="list" href="#list-bass" role="tab" aria-controls="messages">Bass</a>
      <a class="list-group-item list-group-item-action" data-toggle="list" href="#list-keyboard" role="tab" aria-controls="settings">Keyboard</a>
      <a class="list-group-item list-group-item-action" data-toggle="list" href="#list-piano" role="tab" aria-controls="settings">Piano</a>
      <a class="list-group-item list-group-item-action" data-toggle="list" href="#list-flute" role="tab" aria-controls="settings">Flute</a>
      <a class="list-group-item list-group-item-action" data-toggle="list" href="#list-cello" role="tab" aria-controls="settings">Cello</a>
      <a class="list-group-item list-group-item-action" data-toggle="list" href="#list-clarinet" role="tab" aria-controls="settings">Clarinet</a>
      <a class="list-group-item list-group-item-action" data-toggle="list" href="#list-accordion" role="tab" aria-controls="settings">Accordion</a>
      <a class="list-group-item list-group-item-action" data-toggle="list" href="#list-saxophone" role="tab" aria-controls="settings">Saxophone</a>
      <a class="list-group-item list-group-item-action" data-toggle="list" href="#list-violin" role="tab" aria-controls="settings">Violin</a>
      <a class="list-group-item list-group-item-action" data-toggle="list" href="#list-drums" role="tab" aria-controls="settings">Drums</a>
    </div>
  </div>

  <div class="col-10 p-0 m-0">
    <div class="tab-content" id="nav-tabContent">

      <div class="tab-pane fade show active" id="list-all" role="tabpanel" aria-labelledby="list-home-list">
        <section class="py-5">
          <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">

              <% @instruments.each do |instrument| %>
                <%= show_instrument(instrument, instrument.name, instrument.model, instrument.brand, instrument.price, instrument.photo, '') %>
              <% end %>

            </div>
          </div>
        </section>
      </div>

      <div class="tab-pane fade" id="list-guitar" role="tabpanel" aria-labelledby="list-profile-list">
        <section class="py-5">
          <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">

              <% @instruments.each do |instrument| %>
                <%= show_instrument(instrument, instrument.name, instrument.model, instrument.brand, instrument.price, instrument.photo, 'Guitar') %>
              <% end %>

            </div>
          </div>
        </section>
      </div>

      <div class="tab-pane fade" id="list-electric-guitar" role="tabpanel" aria-labelledby="list-profile-list">
        <section class="py-5">
          <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">

              <% @instruments.each do |instrument| %>
                <%= show_instrument(instrument, instrument.name, instrument.model, instrument.brand, instrument.price, instrument.photo, 'Electric guitar') %>
              <% end %>

            </div>
          </div>
        </section>
      </div>

      <div class="tab-pane fade" id="list-bass" role="tabpanel" aria-labelledby="list-messages-list">
        <section class="py-5">
          <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">

              <% @instruments.each do |instrument| %>
                <%= show_instrument(instrument, instrument.name, instrument.model, instrument.brand, instrument.price, instrument.photo, 'Bass') %>
              <% end %>

            </div>
          </div>
        </section>
      </div>

      <div class="tab-pane fade" id="list-keyboard" role="tabpanel" aria-labelledby="list-settings-list">
        <section class="py-5">
          <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">

              <% @instruments.each do |instrument| %>
                <%= show_instrument(instrument, instrument.name, instrument.model, instrument.brand, instrument.price, instrument.photo, 'Keyboard') %>
              <% end %>

            </div>
          </div>
        </section>
      </div>

      <div class="tab-pane fade" id="list-piano" role="tabpanel" aria-labelledby="list-settings-list">
        <section class="py-5">
          <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">

              <% @instruments.each do |instrument| %>
                <%= show_instrument(instrument, instrument.name, instrument.model, instrument.brand, instrument.price, instrument.photo, 'Piano') %>
              <% end %>

            </div>
          </div>
        </section>
      </div>

      <div class="tab-pane fade" id="list-flute" role="tabpanel" aria-labelledby="list-settings-list">
        <section class="py-5">
          <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">

              <% @instruments.each do |instrument| %>
                <%= show_instrument(instrument, instrument.name, instrument.model, instrument.brand, instrument.price, instrument.photo, 'Flute') %>
              <% end %>

            </div>
          </div>
        </section>
      </div>

      <div class="tab-pane fade" id="list-cello" role="tabpanel" aria-labelledby="list-settings-list">
        <section class="py-5">
          <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">

              <% @instruments.each do |instrument| %>
                <%= show_instrument(instrument, instrument.name, instrument.model, instrument.brand, instrument.price, instrument.photo, 'Cello') %>
              <% end %>

            </div>
          </div>
        </section>
      </div>

      <div class="tab-pane fade" id="list-clarinet" role="tabpanel" aria-labelledby="list-settings-list">
        <section class="py-5">
          <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">

              <% @instruments.each do |instrument| %>
                <%= show_instrument(instrument, instrument.name, instrument.model, instrument.brand, instrument.price, instrument.photo, 'Clarinet') %>
              <% end %>

            </div>
          </div>
        </section>
      </div>

      <div class="tab-pane fade" id="list-accordion" role="tabpanel" aria-labelledby="list-settings-list">
        <section class="py-5">
          <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">

              <% @instruments.each do |instrument| %>
                <%= show_instrument(instrument, instrument.name, instrument.model, instrument.brand, instrument.price, instrument.photo, 'Accordion') %>
              <% end %>

            </div>
          </div>
        </section>
      </div>

      <div class="tab-pane fade" id="list-saxophone" role="tabpanel" aria-labelledby="list-settings-list">
        <section class="py-5">
          <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">

              <% @instruments.each do |instrument| %>
                <%= show_instrument(instrument, instrument.name, instrument.model, instrument.brand, instrument.price, instrument.photo, 'Saxophone') %>
              <% end %>

            </div>
          </div>
        </section>
      </div>

      <div class="tab-pane fade" id="list-violin" role="tabpanel" aria-labelledby="list-settings-list">
        <section class="py-5">
          <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">

              <% @instruments.each do |instrument| %>
                <%= show_instrument(instrument, instrument.name, instrument.model, instrument.brand, instrument.price, instrument.photo, 'Violin') %>
              <% end %>

            </div>
          </div>
        </section>
      </div>

      <div class="tab-pane fade" id="list-drums" role="tabpanel" aria-labelledby="list-settings-list">
        <section class="py-5">
          <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">

              <% @instruments.each do |instrument| %>
                <%= show_instrument(instrument, instrument.name, instrument.model, instrument.brand, instrument.price, instrument.photo, 'Drums') %>
              <% end %>

            </div>
          </div>
        </section>
      </div>

    </div>
  </div>
</div>

<%= render 'layouts/footer' %>

app/views/instruments/new.html.erb
<div class="container light-style flex-grow-1 container-p-y">

<h4 class="font-weight-bold py-3 mb-4">
  New Instruments
</h4>

<%= render "form", instrument: @instrument %>

</div>

app/views/instruments/show.html.erb
<%= render 'layouts/navbar' %>

<section class="py-5">
  <div class="container px-4 px-lg-5 my-5">
    <div class="row gx-4 gx-lg-5 align-items-center">
      <div class="col-md-6"><%= image_tag @instrument.photo, style:'card-img-top mb-5 mb-md-0', size:'498x581' if @instrument.photo.attached? %></div>
      <div class="col-md-6">
        <div class="small mb-1">SKU: BST-498<%= @instrument.id %></div>
        <h1 class="display-5 fw-bolder"><%= @instrument.name %> <%= @instrument.model %> <%= @instrument.brand %></h1>
        <div class="fs-5 mb-5">
            <span>R$ <%= @instrument.price %></span>
        </div>
        <p class="lead">Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium at dolorem quidem modi. Nam sequi consequatur obcaecati excepturi alias magni, accusamus eius blanditiis delectus ipsam minima ea iste laborum vero?</p>
        <div class="d-flex">
            <input class="form-control text-center me-3" id="inputQuantity" type="num" value="1" style="max-width: 3rem" />
            <button class="btn btn-outline-dark flex-shrink-0" type="button">
                <i class="bi-cart-fill me-1"></i>
                Add to cart
            </button>
        </div>
        <% if current_user && current_user.admin %>
          <p class="font-italic mt-5">Admin options:</p>
          <div class="d-flex align-items-end mt-1">
            <%= link_to "Edit", edit_instrument_path(@instrument), class:'btn btn-primary me-1' %>
            <%= link_to "Destroy", instrument_path(@instrument), class:'btn btn-danger',
            method: :delete,
            data: { confirm: "Are you sure?" } %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

<div class="mb-5">
  <hr style="width:auto;margin-right:150px;margin-left:150px;background-color:black;">
  <h2 class="text-center my-4 font-weight-light">DESCRIPTION</h2>
  <%= simple_format(@instrument.description, class:'font-weight-light', style:'margin-right:150px;margin-left:150px;') %>
</div>
  
<section class="py-5 bg-light">
  <div class="container px-4 px-lg-5 mt-5">
    <h2 class="fw-bolder mb-4">Featured Products</h2>
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">

      <% @instruments.take(5).each do |instrument| %>
        <div class="col mx-2 px-0 hover-shadow" style="max-width:190px;max-height:550px;">
          <div class="card h-100">
            <% if instrument.photo.attached? %>
              <%= image_tag instrument.photo, class: 'card-img-top', style: 'height:350px;width:auto;' if instrument.photo.attached? %>
            <% else %>
              <img class="card-img-top" style="height:350px;background-color:gray;border:solid 1px gray;">
            <% end %>
            <div class="card-body p-4">
              <div class="text-center">
                <h5 class="fw-bolder"><%= instrument.name %>, <%= instrument.model %> <%= instrument.brand %></h5>
                <div class="d-flex justify-content-center small text-warning mb-2">
                  <div class="bi-star-fill"></div>
                  <div class="bi-star-fill"></div>
                  <div class="bi-star-fill"></div>
                  <div class="bi-star-fill"></div>
                  <div class="bi-star-fill"></div>
                </div>
                <p class="card-text">R$ <%= instrument.price %></p>
              </div>
            </div>
          </div>
          <%= link_to '', shop_path(instrument), class:'mt-auto stretched-link' %>
        </div>
      <% end %>

    </div>
  </div>
</section>

<%= render 'layouts/footer' %>