config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :instruments, :except => [:index, :show]
  resources :users, :except => [:new]
  resources :shop, controller: 'instruments', :only => [:index, :show]
  resources :product_types

  get 'contacts', to: 'contacts#index'
  get :shopping_carts, :path => 'cart', to: 'shopping_carts#index'

  root to: 'welcome#index'
end

app/views/layouts/_footer.html.erb
<div class="d-flex flex-column min-vh-100">
  <footer class="text-center text-lg-start bg-dark text-muted mt-5 mt-auto">

    <section class="text-white d-flex">
      <div class="container text-center text-md-start mt-5">
        <div class="row mt-3">
          <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
            <h6 class="text-uppercase fw-bold mb-4">
              <i class="fas fa-gem me-3"></i>Instruments Store
            </h6>
            <p>
              Instruments store is a store designed solely for the purpose of growth in the 
              study of the web programming field.
            </p>
          </div>

          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
            <h6 class="text-uppercase fw-bold mb-4">
              Social Midia
            </h6>
            <p><a href="https://matheusalves00.github.io/portfolio/" class="text-reset">Portfolio</a></p>
            <p><a href="https://www.linkedin.com/in/matheusalves00" class="text-reset">Linkedin</a></p>
            <p><a href="https://github.com/MatheusAlves00/instruments-store" class="text-reset">Github</a></p>
          </div>

          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
            <h6 class="text-uppercase fw-bold mb-4">
              Contact
            </h6>
            <p><i class="fas fa-home me-3"></i> Pernambuco, Brazil</p>
            <p>
              <i class="fas fa-envelope me-3"></i>
              suport@instrumentstore.com
            </p>
            <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
            <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
          </div>
        </div>
      </div>
    </section>

    <div class="text-center text-white p-4" style="background-color: rgba(0, 0, 0, 0.05);">
      © 2024 Copyright. All right reserved.
    </div>
  </footer>
</div>

app/views/layouts/_navbar.html.erb
<script src="https://kit.fontawesome.com/99af388dfc.js" crossorigin="anonymous"></script>

<script>
  $(document).on('turbolinks:load', function() {
    $('.dropdown-toggle').dropdown()
  })
</script>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark" data-turbolinks="false">
  <div class="container-fluid">
    <a href="<%= root_path %>" class="navbar-brand mx-4 d-flex flex-row align-items-center">
      <i class="fa-solid fa-guitar pe-2" style="font-size:1.5em;"></i>
      <span style="font-size:1.2em;">Instrument Store</span>
    </a>
  </div>

  <div class="container-fluid collapse navbar-collapse">
    <div class="" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link <%= request.path == root_path ? 'active' : '' %>" href="<%= root_path %>">Home</a>
        <a class="nav-link <%= request.path == shop_index_path || params[:id] ? 'active' : '' %>" href="<%= shop_index_path %>">Shop</a>
        <a class="nav-link <%= request.path == shopping_carts_path ? 'active' : '' %>" href="<%= shopping_carts_path %>">Cart</a>
        <a class="nav-link <%= request.path == contacts_path ? 'active' : '' %>" href="<%= contacts_path %>">Contacts</a>
      </div>
    </div>

    <form class="d-flex">
      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
      <div class="dropdown">
        <% if user_signed_in? %>
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.email %>
          </button>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to 'Manage Account', user_path(current_user.id), class: 'dropdown-item' %>
            <hr class="dropdown-divider">
            <% if current_user.admin == true %>
              <a class="dropdown-item disabled" href="#">Admin Options</a>
              <%= link_to 'Add Instrument', new_instrument_path, class:"dropdown-item text-primary" %>
              <%= link_to 'Show Users', users_path, class:"dropdown-item text-success" %>
              <hr class="dropdown-divider">
            <% end %>
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
          </div>
        <% else %>
          <%= link_to 'Login', new_user_session_path, class: 'btn btn-outline-success ms-2' %>
        <% end %>
      </div>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstrumentsStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>